const $=id=>document.getElementById(id);
const today=()=>new Date().toISOString().slice(0,10);
const defaults={name:'',phone:'',lang:'uz',coins:0,dailyEarned:0,dailyDate:today(),tasks:0,streak:0,badges:0,level:1,photo:null,before:null,after:null,notifications:false,theme:'#16A34A',tx:[]};
let state=Object.assign({},defaults,JSON.parse(localStorage.getItem('ecoHeroState')||'null')||{});
function rollover(){if(state.dailyDate!==today()){state.dailyDate=today();state.dailyEarned=0;save(false)}}
const T={uz:{welcome:"Boshlash uchun ma'lumotlaringizni kiriting",name:'Ism',phone:'Telefon raqami',language:'Til',continue:'Davom etish →',home:'Bosh sahifa',map:'Xarita',rank:'Reyting',rewards:"Sovg'alar",profile:'Profil',settings:'Sozlamalar',start:'Topshiriqni boshlash',settingsText:"Ilovani o'zingizga moslang.",daily:'Bugungi limit',coin:'EcoCoin',before:'1-rasm: Tozalashdan oldin',after:'2-rasm: Tozalashdan keyin',saveBefore:'1-rasmni tasdiqlash',verify:'Tasdiqlash',notifications:'Bildirishnomalar',theme:'Ilova rangi'},ru:{welcome:'Введите данные для начала',name:'Имя',phone:'Номер телефона',language:'Язык',continue:'Продолжить →',home:'Главная',map:'Карта',rank:'Рейтинг',rewards:'Подарки',profile:'Профиль',settings:'Настройки',start:'Начать задание',settingsText:'Настройте приложение.',daily:'Дневной лимит',coin:'EcoCoin',before:'Фото 1: До уборки',after:'Фото 2: После уборки',saveBefore:'Подтвердить фото 1',verify:'Подтвердить',notifications:'Уведомления',theme:'Цвет приложения'},kk:{welcome:'Бастау үшін деректеріңізді енгізіңіз',name:'Аты',phone:'Телефон нөмірі',language:'Тіл',continue:'Жалғастыру →',home:'Басты бет',map:'Карта',rank:'Рейтинг',rewards:'Сыйлықтар',profile:'Профиль',settings:'Баптаулар',start:'Тапсырманы бастау',settingsText:'Қолданбаны баптаңыз.',daily:'Күндік лимит',coin:'EcoCoin',before:'1-сурет: Тазалауға дейін',after:'2-сурет: Тазалаудан кейін',saveBefore:'1-суретті растау',verify:'Растау',notifications:'Хабарламалар',theme:'Қолданба түсі'},en:{welcome:'Enter your details to get started',name:'Name',phone:'Phone number',language:'Language',continue:'Continue →',home:'Home',map:'Map',rank:'Leaderboard',rewards:'Rewards',profile:'Profile',settings:'Settings',start:'Start task',settingsText:'Customize the app.',daily:'Daily limit',coin:'EcoCoin',before:'Photo 1: Before cleaning',after:'Photo 2: After cleaning',saveBefore:'Confirm photo 1',verify:'Confirm',notifications:'Notifications',theme:'App color'},tg:{welcome:'Барои оғоз маълумоти худро ворид кунед',name:'Ном',phone:'Рақами телефон',language:'Забон',continue:'Идома →',home:'Асосӣ',map:'Харита',rank:'Рейтинг',rewards:'Тӯҳфаҳо',profile:'Профил',settings:'Танзимот',start:'Оғози супориш',settingsText:'Барномаро танзим кунед.',daily:'Маҳдудияти рӯзона',coin:'EcoCoin',before:'Сурати 1: Пеш аз тозакунӣ',after:'Сурати 2: Пас аз тозакунӣ',saveBefore:'Тасдиқи сурати 1',verify:'Тасдиқ',notifications:'Огоҳиномаҳо',theme:'Ранги барнома'}};
function tr(k){return (T[state.lang]||T.uz)[k]||k}
function save(update=true){localStorage.setItem('ecoHeroState',JSON.stringify(state));applyTheme();if(update)updateHeader()}
function applyTheme(){document.documentElement.style.setProperty('--green',state.theme||'#16A34A')}
function updateHeader(){if($('coinTop'))$('coinTop').textContent=state.coins.toLocaleString();if($('miniName'))$('miniName').textContent=state.name||'Eco Hero';if($('miniLevel'))$('miniLevel').textContent=levelName();if(state.photo&&$('miniAvatar'))$('miniAvatar').innerHTML='<img src="'+state.photo+'" alt="Profil">'}
function toast(x){$('toast').textContent=x;$('toast').classList.add('show');clearTimeout(window.toastT);window.toastT=setTimeout(()=>$('toast').classList.remove('show'),2300)}
function toggleSide(){$('side').classList.toggle('open')}
function closeSide(){if(window.innerWidth<=900)$('side').classList.remove('open')}
function phoneOk(p){return /^\+?998\s?\d{2}\s?\d{3}\s?\d{2}\s?\d{2}$/.test(p.replace(/[()-]/g,''))}
function registerUser(){const n=$('regName').value.trim(),p=$('regPhone').value.trim();if(n.length<2)return toast('Ismingizni kiriting.');if(!phoneOk(p))return toast('Telefon raqamini +998 90 123 45 67 ko‘rinishida kiriting.');state.name=n;state.phone=p;state.lang=$('regLang').value;state.coins=0;state.dailyEarned=0;state.dailyDate=today();save();$('onboarding').classList.add('hidden');go('home');toast('Xush kelibsiz, '+n+'! 🌱');scheduleNotification()}
function showOnboarding(){ $('onboarding').classList.remove('hidden');$('regName').value=state.name||'';$('regPhone').value=state.phone||'';$('regLang').value=state.lang||'uz' }
function applyLang(){document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=tr(e.dataset.i18n))}
function levelName(){return state.coins<50?'Yangi ishtirokchi':state.coins<200?'Tozalik yordamchisi':state.coins<500?'Faol ko‘ngilli':state.coins<1000?'Tozalik faoli':state.coins<2500?'Eco Hero':'Eco Leader'}
function shell(x){$('app').innerHTML='<div class="wrap">'+x+'</div>';updateHeader();applyLang();}
function go(page){closeSide();rollover();({home,task,mapPage,rank,rewards,wallet,profile,settings}[page]||home)();window.scrollTo({top:0,behavior:'smooth'})}
function badge(e,n,lock){return '<div class="badge '+(lock?'locked':'')+'"><div class="e">'+e+'</div><b>'+n+'</b><small>'+(lock?'🔒 Yopiq':'✓ Ochildi')+'</small></div>'}
function home(){const remain=100-state.dailyEarned;const pct=state.dailyEarned; shell('<section class="hero"><div><p>Salom, '+(state.name||'Eco Hero')+'! 👋</p><h1>Har bir toza joy — katta o‘zgarish.</h1><p>Har bir tasdiqlangan tozalash uchun <b>+5 🪙</b>. Kunlik maksimum 100 🪙.</p><button class="btn light" onclick="go(\'task\')">🧹 '+tr('start')+'</button></div><div class="hero-box"><span>'+tr('coin')+'</span><strong>🪙 '+state.coins+'</strong><span>'+levelName()+' · 🔥 '+state.streak+' kun</span></div></section><div class="section"><h2>📊 Bugungi limit</h2><b>'+state.dailyEarned+' / 100 🪙</b></div><div class="card"><div class="progress"><i style="width:'+pct+'%"></i></div><p class="muted">'+(remain>0?'Bugun yana '+remain+' 🪙 olish mumkin. Limit ertaga 0 dan qayta hisoblanadi.':'Bugungi 100 🪙 limit tugadi. Mavjud coinlaringiz saqlanadi; yangi kun boshlanganda limit qayta ochiladi.')+'</p></div><div class="section"><h2>📈 Natijangiz</h2></div><div class="grid g4"><div class="card stat">🪙<b>'+state.coins+'</b><span>EcoCoin</span></div><div class="card stat">🧹<b>'+state.tasks+'</b><span>Topshiriq</span></div><div class="card stat">🔥<b>'+state.streak+'</b><span>Streak</span></div><div class="card stat">🏅<b>'+state.badges+'</b><span>Badge</span></div></div><div class="section"><h2>🏅 Yutuqlar</h2></div><div class="badges">'+badge('🌱','Birinchi qadam',state.tasks<1)+badge('📸','Birinchi topshiriq',state.tasks<1)+badge('🔥','7 kun',state.streak<7)+badge('🌍','50 hudud',state.tasks<50)+'</div>')}
function task(){rollover();const disabled=state.dailyEarned>=100; shell('<div class="page"><h1>🧹 '+tr('start')+'</h1><p>Avval 1-rasm. Uni tasdiqlaganingizdan keyin 2-rasm ochiladi.</p><div class="limit-card">🪙 Bugun: <b>'+state.dailyEarned+'/100</b> · Har tasdiq <b>+5 🪙</b></div><div class="card photo-step"><h3>📸 '+tr('before')+'</h3><div class="camera"><div><div class="camera-icon">📷</div><p>Faqat 1-rasm shu yerda ochiladi.</p><input id="beforeFile" type="file" accept="image/*" capture="environment" onchange="preview(this,\'beforePreview\')"></div></div><div class="frame"><img id="beforePreview" class="preview" alt="Oldingi rasm"></div><button class="btn primary full" onclick="saveBefore()" '+(disabled?'disabled':'')+'>'+tr('saveBefore')+' →</button><div id="beforeStatus" class="status"></div></div><div id="afterStep" class="card photo-step locked-step"><h3>✨ '+tr('after')+'</h3><div id="afterMessage" class="notice">🔒 Avval 1-rasmni yuklang va tasdiqlang. Shundan keyin 2-rasm ochiladi.</div><div class="camera hidden-area" id="afterCamera"><div><div class="camera-icon">✨</div><p>Tozalangandan keyingi holat.</p><input id="afterFile" type="file" accept="image/*" capture="environment" onchange="preview(this,\'afterPreview\')"></div></div><div class="frame"><img id="afterPreview" class="preview" alt="Keyingi rasm"></div><button id="verifyBtn" class="btn primary full" onclick="verify()" disabled>'+tr('verify')+' (+5 🪙)</button></div></div>');if(state.before)restoreBefore();}
function restoreBefore(){const im=$('beforePreview');im.src=state.before;im.style.display='block';$('beforeStatus').innerHTML='✅ 1-rasm tasdiqlangan. Endi 2-rasm ochildi.';unlockAfter()}
function preview(input,id){const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=e=>{const im=$(id);im.src=e.target.result;im.style.display='block';if(id==='beforePreview')$('beforeStatus').innerHTML='📸 Rasm tayyor. Endi «1-rasmni tasdiqlash» tugmasini bosing.';if(id==='afterPreview'){$('verifyBtn').disabled=false;$('afterMessage').textContent='✅ 2-rasm tayyor. Endi tasdiqlang.'}};r.readAsDataURL(f)}
function saveBefore(){const im=$('beforePreview');if(!im.src||im.src==='')return toast('Avval 1-rasmni tanlang.');state.before=im.src;save();unlockAfter();toast('1-rasm tasdiqlandi. 2-rasm ochildi 📸')}
function unlockAfter(){const box=$('afterStep');if(!box)return;box.classList.remove('locked-step');$('afterMessage').className='success';$('afterMessage').textContent='✅ 1-rasm qabul qilindi. Endi tozalang va 2-rasmni yuboring.';$('afterCamera').classList.remove('hidden-area');if(state.after){$('afterPreview').src=state.after;$('afterPreview').style.display='block';$('verifyBtn').disabled=false}}
function verify(){if(state.dailyEarned>=100)return toast('Bugungi 100 🪙 limit tugagan. Ertaga davom etasiz.');const before=$('beforePreview'),after=$('afterPreview');if(!before.src)return toast('Avval 1-rasmni tasdiqlang.');if(!after.src)return toast('2-rasmni yuklang.');state.after=after.src;save();let p=0;shell('<div class="card verify-card"><div class="big-icon">🤖</div><h1>Tekshirilmoqda...</h1><p>1-rasm va 2-rasm taqqoslanmoqda.</p><div class="progress"><i id="vp" style="width:0%"></i></div><p id="vtext" class="muted">Rasm sifati tekshirilmoqda...</p></div>');const t=setInterval(()=>{p+=20;$('vp').style.width=p+'%';if(p===40)$('vtext').textContent='Tasvirlar taqqoslanmoqda...';if(p>=100){clearInterval(t);approveTask()}},220)}
function approveTask(){state.dailyEarned=Math.min(100,state.dailyEarned+5);state.coins+=5;state.tasks++;state.streak++;state.badges=Math.max(state.badges,Math.min(20,Math.floor(state.tasks/3)));state.tx.unshift({text:'Tasdiqlangan tozalash',amount:5,time:new Date().toLocaleTimeString()});state.before=null;state.after=null;save();shell('<div class="card verify-card"><div class="big-icon">🎉</div><h1>Tasdiqlandi!</h1><div class="reward">+5 🪙</div><p>Bugungi limit: <b>'+state.dailyEarned+'/100 🪙</b></p><p>Umumiy balans: <b>'+state.coins+' 🪙</b></p><button class="btn primary" onclick="go(\'task\')">Yana topshiriq</button> <button class="btn ghost" onclick="go(\'home\')">Bosh sahifa</button></div>');}
function mapPage(){shell('<div class="page"><h1>🗺️ '+tr('map')+'</h1><p>Tozalash hududlari.</p><div class="map"><span class="pin" style="left:15%;top:25%">🔴</span><span class="pin" style="left:48%;top:55%">🟢</span><span class="pin" style="left:75%;top:20%">🔴</span><span class="pin" style="left:60%;top:72%">⭐</span></div></div>')}
function rank(){const a=[['1','Ali','5240'],['2','Bunyodbek','4870'],['3','Sardor','4520'],['4',state.name||'Siz',state.coins],['5','Jasur','3120']];shell('<div class="page"><h1>🏆 '+tr('rank')+'</h1><p>EcoCoin reytingi.</p><div class="card">'+a.map(x=>'<div class="rank"><div class="ranknum">'+x[0]+'</div><div class="avatar">'+x[1][0]+'</div><b>'+x[1]+'</b><span class="rankscore">🪙 '+x[2]+'</span></div>').join('')+'</div></div>')}
function rewards(){const a=[['🎒','Eco Bag',500],['👕','Eco Hero T-Shirt',1000],['🏅','Maxsus medal',1500],['🌱','Eco kit',800]];shell('<div class="page"><h1>🎁 '+tr('rewards')+'</h1><p>EcoCoinlarni sovg‘alarga almashtiring.</p><div class="wallet"><span>Balans</span><strong>🪙 '+state.coins+'</strong></div><div class="grid g4" style="margin-top:16px">'+a.map(x=>'<div class="card"><div class="reward-icon">'+x[0]+'</div><h3>'+x[1]+'</h3><p class="price">🪙 '+x[2]+'</p><button class="btn primary '+(state.coins<x[2]?'disabled':'')+'" onclick="redeem(\''+x[1]+'\','+x[2]+')">Almashtirish</button></div>').join('')+'</div></div>')}
function redeem(n,c){if(state.coins<c)return toast('Coin yetarli emas.');if(!confirm(n+' uchun '+c+' 🪙 sarflansinmi?'))return;state.coins-=c;state.tx.unshift({text:n,amount:-c,time:'Hozir'});save();toast('🎁 Buyurtma qabul qilindi');rewards()}
function wallet(){shell('<div class="page"><h1>🪙 EcoWallet</h1><p>Coinlar tarixi.</p><div class="wallet"><span>Jami balans</span><strong>🪙 '+state.coins+'</strong><span>Bugun: '+state.dailyEarned+'/100 🪙</span></div><div class="card" style="margin-top:16px">'+(state.tx.length?state.tx.map(x=>'<div class="tx"><div><b>'+x.text+'</b><small class="muted">'+x.time+'</small></div><b class="'+(x.amount>0?'plusc':'minusc')+'">'+(x.amount>0?'+':'')+x.amount+' 🪙</b></div>').join(''):'<div class="muted">Hali tranzaksiya yo‘q.</div>')+'</div></div>')}
function profile(){shell('<div class="page"><h1>👤 '+tr('profile')+'</h1><div class="card profile-row">'+(state.photo?'<img class="photo" src="'+state.photo+'" alt="Profil rasmi">':'<div class="photo placeholder">👤</div>')+'<div class="profile-info"><h2>'+state.name+'</h2><p>'+state.phone+'</p><p>'+levelName()+' · 🔥 '+state.streak+' kun</p><input type="file" accept="image/*" onchange="setPhoto(this)"></div></div><div class="section"><h2>📊 Statistika</h2></div><div class="grid g4"><div class="card stat"><b>'+state.tasks+'</b><span>Hudud</span></div><div class="card stat"><b>'+state.coins+'</b><span>Coin</span></div><div class="card stat"><b>'+state.streak+'</b><span>Streak</span></div><div class="card stat"><b>'+state.badges+'</b><span>Badge</span></div></div><div class="section"><h2>🏅 Yutuqlar</h2></div><div class="badges">'+badge('🌱','Birinchi qadam',state.tasks<1)+badge('📸','Birinchi topshiriq',state.tasks<1)+badge('🔥','7 kun',state.streak<7)+badge('🧹','10 hudud',state.tasks<10)+badge('🌍','50 hudud',state.tasks<50)+badge('👑','1000 Coin',state.coins<1000)+badge('💚','Eco Leader',state.coins<2500)+'</div></div>')}
function setPhoto(input){const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=e=>{state.photo=e.target.result;save();profile();toast('Profil rasmi saqlandi 📸')};r.readAsDataURL(f)}
function settings(){
  const colors=['#16A34A','#2563EB','#7C3AED','#DB2777','#EA580C','#0891B2','#65A30D','#334155'];
  const colorButtons=colors.map(c=>`<button class="theme ${state.theme===c?'active':''}" style="background:${c}" onclick="setTheme('${c}')"></button>`).join('');
  shell(`<div class="page">
    <h1>⚙️ ${tr('settings')}</h1><p>${tr('settingsText')}</p>
    <div class="card">
      <div class="tx"><b>🌐 ${tr('language')}</b><select class="input compact" onchange="setLang(this.value)">
        <option value="uz" ${state.lang==='uz'?'selected':''}>O‘zbekcha</option><option value="ru" ${state.lang==='ru'?'selected':''}>Русский</option><option value="kk" ${state.lang==='kk'?'selected':''}>Қазақша</option><option value="en" ${state.lang==='en'?'selected':''}>English</option><option value="tg" ${state.lang==='tg'?'selected':''}>Тоҷикӣ</option>
      </select></div>
      <div class="tx"><b>🔔 ${tr('notifications')}</b><label class="switch"><input type="checkbox" ${state.notifications?'checked':''} onchange="notif(this.checked)"><span></span></label></div>
      <div class="tx"><b>⏱ Eslatma</b><span>1:50 soat</span></div>
      <div class="tx"><b>📱 ${tr('phone')}</b><span class="break">${state.phone}</span></div>
      <div class="tx"><b>👤 ${tr('name')}</b><span class="break">${state.name}</span></div>
    </div>
    <div class="section"><h2>🎨 ${tr('theme')}</h2></div>
    <div class="card"><div class="theme-grid">${colorButtons}</div></div>
    <div class="card effect-card"><h3>✨ Effektlar</h3><p class="muted">Mukofot va tasdiqlash animatsiyasi.</p><button class="btn primary" onclick="effect()">✨ Effektni ko‘rish</button></div>
    <div class="card"><h3>👤 Profil ma'lumotlari</h3><button class="btn ghost" onclick="showOnboarding()">Ism / telefonni o‘zgartirish</button></div>
    <div class="card"><button class="btn ghost" onclick="resetDemo()">Demo ma'lumotlarini 0 ga qaytarish</button></div>
  </div>`);
}
function setLang(l){state.lang=l;save();settings();toast('Til o‘zgartirildi 🌐')}
function setTheme(c){state.theme=c;save();settings();toast('Rang o‘zgartirildi 🎨')}
function effect(){document.body.classList.add('celebrate');setTimeout(()=>document.body.classList.remove('celebrate'),900);toast('✨ Effekt ishladi!')}
function notif(on){state.notifications=on;save();if(on){if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();scheduleNotification();toast('Bildirishnoma yoqildi 🔔')}else{clearTimeout(window.nt);toast('Bildirishnoma o‘chirildi 🔕')}}
function scheduleNotification(){clearTimeout(window.nt);if(!state.notifications)return;window.nt=setTimeout(()=>{if(state.notifications&&'Notification'in window&&Notification.permission==='granted')new Notification('🌱 ECO HERO',{body:'Yangi topshiriq sizni kutmoqda!'});else if(state.notifications)toast('🌱 ECO HERO: yangi topshiriq sizni kutmoqda!');scheduleNotification()},110*60*1000)}
function resetDemo(){localStorage.removeItem('ecoHeroState');location.reload()}
rollover();applyTheme();updateHeader();if(!state.name||!state.phone){showOnboarding()}else{scheduleNotification()}go('home');
